INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project", "Programming", 5000, 20150815, 20151018);


INSERT INTO users (id, name, age) VALUES (1, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (2, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (3, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (4, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (5, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (6, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (7, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (8, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (9, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (10, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (11, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (12, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (13, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (14, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (15, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (16, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (17, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (18, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (19, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (20, "Stacey", 25);


INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
